---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: discord-webhook
  namespace: kube-prometheus-stack
spec:
  encryptedData:
    discord-webhook: AgCXJwJRyfiEp+zak5a2KxqRoUd7AJvQarTFkOq5snPoiIza0OoW5m9BunBsajglLbGz/SvCzfSWMTIoXOCo1/sW4mhPKKNeBH/kdxdFsyUPFlpBRvsmWEHYoUKYZxlYCHcmkCR+WxhGQJkENV2Eel+3n4VMw3jTWPxKfG34KFzAj8WEiZawwBrvyMaQQnFSWS0ieAsFGcENfb+PEku+BxXzcE+47Ez/ElHp2ggEsBXGfEE/tUTLRnbZmhpq1zv72og9DkfTPK1f3kVoheA7ZOYtviP6uxOYDBRar9EMKCxwfNLhK8E6dYqtVwvW8yVk9BeVpcwbPDz1BR2oitxt66vEs5gZLIPzKITJ7R10PgkHuMEO5SxwgqSAkvXZHIpbDJB6f2ylFCoOfyfUnCv/PdXlXuZbkI86Q2PPLZj7w93z5JpBAN2/+c6S5HpWJBJCaW2VSYYxGDri8Hp+k4gVqbMNd0HMvqMkXRYReTgNtzTmHNwWxPQhE5MQ+QAacDWnhMY9jLwo1gWr1wdXiREF9zuIR7mT1E4/rhIpsMv+qUHkYdzS5xW3DuIp+bx/VePhV2mrpWYGhgbeMJR5/ntMP6m3L1SglQFOf+bqY/EmPo0RmnQUQpX8jp6BK/LfKg2NvBUjzzFWe/zCpA8tuPx1fsrvUW1Mu4WW/xOHn9ovxO6zLc4Pxxvbt3y3uoLqUHSKztW9XseRq4z75u1F3QNXz9p8Iap3Dh1cu18EPlNk48vJGbeKkue1gzk7R0XRjslVR0LiinguWAxET9yB6MSn4sCT/ugljciMHGO863DMX8SQ8oeynQOI07ntDRK6HctSBdAXvO1U5aNxBuk3kCR+txdzV/2THaoILnDG5Zqo
  template:
    metadata:
      name: discord-webhook
      namespace: kube-prometheus-stack
