
apiVersion: v1
kind: Secret
metadata:
  name: frame-settings  f
type: Opaque
data:
  ImmichServerUrl: aHR0cDovL2ltbWljaC1zZXJ2ZXI6MjI4Mw==
  ApiKey: Inc5YkJ5amE5ZUFvRkNkcE5BVldqbVE0T1VLeklPUzJKdkM5UEhvMjI2TGci
  WeatherApiKey: NGE5YmIxOTRhN2VkYTE5ZGIwOTA0NmI0Zjc3MzRhYTQ=