
apiVersion: v1
kind: Secret
metadata:
  name: settings
data:
  Settings.yml: General:
  AuthenticationSecret: null
  DownloadImages: false
  RenewImagesDuration: 30
  RefreshAlbumPeopleInterval: 12
  PhotoDateFormat: MM/dd/yyyy
  ImageLocationFormat: 'City,State,Country'
  WeatherApiKey: '4a9bb194a7eda19db09046b4f7734aa4'
  UnitSystem: metric
  WeatherLatLong: '40.730610,-73.935242'
  Webhook: null
  Language: en
  Interval: 45
  TransitionDuration: 2
  ShowClock: true
  ClockFormat: 'hh:mm'
  ClockDateFormat: 'eee, MMM d'
  ShowProgressBar: true
  ShowPhotoDate: true
  ShowImageDesc: true
  ShowPeopleDesc: true
  ShowAlbumName: true
  ShowImageLocation: true
  PrimaryColor: '#f5deb3'
  SecondaryColor: '#000000'
  Style: none
  BaseFontSize: 17px
  ShowWeatherDescription: true
  WeatherIconUrl: 'https://openweathermap.org/img/wn/{IconId}.png'
  ImageZoom: true
  ImagePan: false
  ImageFill: false
  Layout: splitview
Accounts:
  - ImmichServerUrl: http://immich-server:2283
    ApiKey: "24Z0kCT89KxFDSwg1oZ8zea7wutx8CKh6l13CneAV8"
    ImagesFromDate: null
    ShowMemories: false
    ShowFavorites: false
    ShowArchived: false
    ImagesFromDays: null
    ImagesUntilDate: null
    Rating: null
    Albums:
      - FotoFrame
    
